import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import "./globals.css";

import AntdThemeRegistry from "@/lib/antd/registry";
import StyledComponentsRegistry from "@/lib/styled/registry";
import StoreProviderRegistry from "@/lib/store/registry";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Adobe Headless",
  description: "Generated by create ranger theme cli",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <AntdRegistry>
            <AntdThemeRegistry>
              <StoreProviderRegistry>
                <Header />
                {children}
              </StoreProviderRegistry>
            </AntdThemeRegistry>
          </AntdRegistry>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
