import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import "./globals.css";

import { getClient } from "@/lib/apollo/client";
import { GET_STORE_CONFIG } from "@/graphql/queries/getStoreConfig";
import AntdThemeRegistry from "@/lib/antd/registry";
import StyledComponentsRegistry from "@/lib/styled/registry";
import ApolloRegistry from "@/lib/apollo/registry";
import StoreProviderRegistry from "@/lib/store/registry";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Adobe Headless",
  description: "Generated by create ranger theme cli",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const { data } = await getClient().query({ query: GET_STORE_CONFIG });

  return (
    <html lang="en">
      <body>
        <ApolloRegistry>
          <StoreProviderRegistry initState={data}>
            <StyledComponentsRegistry>
              <AntdRegistry>
                <AntdThemeRegistry>
                  <Header />
                  {children}
                </AntdThemeRegistry>
              </AntdRegistry>
            </StyledComponentsRegistry>
          </StoreProviderRegistry>
        </ApolloRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
